---
title: ScannedMedia
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
    heading: Have you read our latest blog posts?
  uploads:
    title: Uploads
    output: true
  work:
    title: work
    output: true
    image: "/uploads/photo-1432888498266-38ffec3eaf0a.png"
    heading: A bit about us, and our clients
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: John Doe
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: works
    subtitle: Service Catagories
    head-image: 
    columns:
    - column-size: is-header
      image: 
    - column-size: is-12
      image: 
      is-body: true
- scope:
    path: ''
    type: testimonials
  values:
    author: John Doe
permalink: pretty
menu:
- title: work
  url: "/work/"
- title: blog
  url: "/blog/"
- title: hire us
  url: "/hire-us/"
logo: "/uploads/SM-logo-horizontal-color.svg"
url: https://scanned.media
plugins:
- jekyll-sitemap
foot:
- title: Address
  url: https://www.google.com/maps/place/Scanned+Media+LLC/@47.651702,-117.4323351,17z/data=!3m1!4b1!4m5!3m4!1s0x549e19fd66fa260d:0x5f728f7abf0929!8m2!3d47.6516984!4d-117.4301411
  is-link: true
  items:
  - '400 S Jefferson St #408,'
  - Spokane, Wa 99204
- title: Contact
  items:
  - M-F 8am to 5pm
  - <a href="tel:+15097207833" target="_Blank">509.720.7833</a>
  - <a href="mailto:info@scannedmedia.com" target="_Blank">info@scannedmedia.com</a>
- title: Services
  items:
  - Apps
  - Branding
  - Web
  - Photography
- title: " &nbsp; "
  items:
  - Videography
  - Drone
  - Social Media Management
  - Targeted Paid Ads
- title: social
  is-social: true
  icons:
  - icon: facebook
    url: https://www.facebook.com/scannedmedia/
  - icon: instagram
    url: https://www.instagram.com/scannedmediacreativefirm/
  - icon: linkedin
    url: https://www.linkedin.com/in/noahbotnick/
contact:
  bg-image: "/uploads/contact-bg-image.jpeg"
  title: Let's start a project!
  name: First and Last Name
  phone: Phone Number
  email: Email
  org: Company/Organization
  website: Website / Optional
  services:
  - Apps
  - Branding
  - Web
  - Photography
  - Videography
  - Drone
  - Social Media Management
  - Targeted Paid Ads
  message: Message
