---
title: smedia
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
    heading: Have you read our latest blog posts?
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: work
    output: true
    image: "/uploads/photo-1432888498266-38ffec3eaf0a.png"
    heading: A bit about us, and our clients
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: John Doe
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: works
    subtitle: branding + identity
    head-image: 
    columns:
    - column-size: is-header
      image: "/uploads/cole-sagerArtboard-4-bg-image-.jpg"
    - column-size: is-12
      image: "/uploads/cole-sagerArtboard-5-bg-image-.jpg"
      is-body: true
    - column-size: is-6
      title: '01'
      subtitle: logo
      para: Be The Impact
      is-catagory: true
    - column-size: is-6
      image: 
    - column-size: is-6
      image: 
    - column-size: is-12
      image: 
    - column-size: is-6
      image: 
    - column-size: is-6
      title: '02'
      subtitle: font
      para: Supporting Type
      is-catagory: true
    - column-size: is-6
      image: 
    - column-size: is-6
      image: 
    - column-size: is-12
      title: '03'
      subtitle: collateral
      para: Additional Material
      is-catagory: true
    - column-size: is-6
      image: 
    - column-size: is-6
      image: 
- scope:
    path: ''
    type: testimonials
  values:
    author: John Doe
permalink: pretty
url: https://www.smedia.siteleaf.net
menu:
- title: work
  url: "/work/"
- title: blog
  url: "/blog/"
- title: hire us
  url: "/contact-us/"
logo: "/uploads/SM-logo-horizontal-color.svg"
foot:
- title: Address
  items:
  - '400 S Jefferson St #408,'
  - Spokane, Wa 99204
- title: Contact
  items:
  - M-F 8am to 5pm
  - 509.720.7833
  - info@scannedmedia.com
- title: Services
  items:
  - Apps
  - Branding
  - Web
- title: social
  is-social: true
  icons:
  - Icon: facebook
    url: 
  - Icon: instagram
    url: 
  - Icon: linkedin
    url: 
  - Icon: google-plus-square
    url: 
